# Generated by Django 3.0.8 on 2020-07-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='link',
            table='links',
        ),
    ]
